document:
  name: Piano di transizione al digitale della Presidenza del Consiglio dei Ministri
  description: |
    Il piano definisce la strategia per il passaggio al digitale della PCM.
  tags:
    - topic
    - related topic
    - amazing project
